// Usage: node tools/build.js   -> writes infosys-se/data/extra.js (+ a preview page in the scratch dir when PREVIEW is set)
const fs = require('fs'), path = require('path');
const L = require('./lib');
const gens = ['./gen-pdf50.js'].concat(fs.existsSync(path.join(__dirname, 'gen-master.js')) ? ['./gen-master.js'] : [], fs.existsSync(path.join(__dirname, 'gen-bank.js')) ? ['./gen-bank.js'] : []);
gens.forEach(g => require(g));
const qs = L.bank;
const ids = new Set(); qs.forEach(q => { if (ids.has(q.id)) throw new Error('duplicate id ' + q.id); ids.add(q.id); });
let mocks = [];
if (fs.existsSync(path.join(__dirname, 'mocks.js'))) mocks = require('./mocks.js')(qs);
const sets=[],setIdx=new Map();qs.forEach(q=>{if(q.set){if(!setIdx.has(q.set)){setIdx.set(q.set,sets.length);sets.push(q.set);}q.setk=setIdx.get(q.set);}});
const slim=qs.map(q=>{const c={...q};delete c.set;return c;});
const out = `// Generated by tools/build.js - do not edit by hand.\n(function(){var X=${JSON.stringify({ questions: slim, sets, mocks })};\nX.questions.forEach(function(q){if(q.setk!==undefined){q.set=X.sets[q.setk];delete q.setk;}});
window.DATA.questions.push.apply(window.DATA.questions,X.questions);window.DATA.mocks.push.apply(window.DATA.mocks,X.mocks);})();\n`;
fs.writeFileSync(path.join(__dirname, '..', 'infosys-se', 'data', 'extra.js'), out);
console.log('extra.js written:', qs.length, 'questions,', mocks.length, 'mocks,', (out.length / 1024).toFixed(0) + ' KB');
if (process.env.PREVIEW) {
  const html = `<!doctype html><meta charset=utf-8><link rel=stylesheet href="file://${path.resolve(__dirname, '../infosys-se/style.css')}"><body><main class=wrap>` +
    qs.filter(q => (!process.env.SEC || q.sec === process.env.SEC) && q.id >= +(process.env.MINID || 0)).map(q => `<div class=panel style="margin:10px 0"><div class=eyebrow>#${q.id} ${q.sec} | ${q.topic}${q.sub ? ' / ' + q.sub : ''}</div><div class=qbody>${q.set || ''}${q.q}</div><ol type=A>${q.opts.map((o, i) => `<li ${i === q.ans ? 'style="font-weight:700"' : ''}>${o}</li>`).join('')}</ol><div class=exp>${q.exp}</div></div>`).join('') + '</main>';
  fs.writeFileSync(process.env.PREVIEW, html);
}
