// Die-solver: faces indexed U0 D1 F2 B3 L4 R5. Rotations generated by closure.
const compose = (p, q) => q.map(i => p[i]); // apply q after p on position arrays
const rotV = [0, 1, 4, 5, 3, 2].map((_, i) => i); // placeholder
// rotate about vertical axis: F->R, R->B, B->L, L->F  (new[position] = old[source])
const RV = [0, 1, 4, 5, 3, 2]; // new F=old L, new B=old R, new L=old B, new R=old F
const RH = [2, 3, 1, 0, 4, 5]; // new U=old F, new D=old B, new F=old D, new B=old U
function group() {
  const id = [0, 1, 2, 3, 4, 5], seen = new Map([[id.join(), id]]), q = [id];
  while (q.length) { const g = q.pop(); for (const r of [RV, RH]) { const n = r.map(i => g[i]); const k = n.join(); if (!seen.has(k)) { seen.set(k, n); q.push(n); } } }
  return [...seen.values()];
}
const G = group();
function perms(a) { if (a.length <= 1) return [a]; return a.flatMap((x, i) => perms([...a.slice(0, i), ...a.slice(i + 1)]).map(p => [x, ...p])); }
// labelling: array of 6 numbers for positions U D F B L R. view under rotation g: [lab[g[0]], lab[g[2]], lab[g[5]]]
function consistent(views) {
  const out = [];
  for (const lab of perms([1, 2, 3, 4, 5, 6])) {
    const trip = new Set(G.map(g => [lab[g[0]], lab[g[2]], lab[g[5]]].join()));
    if (views.every(v => trip.has(v.join()))) out.push(lab);
  }
  return out;
}
function opposite(lab, n) { const i = lab.indexOf(n); return lab[i ^ 1]; }
function rightOf(lab, top, front) { for (const g of G) if (lab[g[0]] === top && lab[g[2]] === front) return lab[g[5]]; }
module.exports = { consistent, opposite, rightOf, G };
if (require.main === module) {
  console.log('group', G.length);
  for (const [name, views] of [['d1', [[3, 2, 4], [6, 1, 3]]], ['d2', [[4, 1, 5], [2, 6, 1]]], ['d3', [[5, 6, 3], [1, 4, 5]]]]) {
    const labs = consistent(views); const uniq = new Set(labs.map(l => [0, 2, 4].map(i => [l[i], l[i + 1]].sort().join('-')).sort().join('|')));
    console.log(name, 'labellings', labs.length, 'distinct pairings', uniq.size, [...uniq]);
    console.log(' opp3', new Set(labs.map(l => opposite(l, 3))), 'opp6', new Set(labs.map(l => opposite(l, 6))), 'right|3top,6front', new Set(labs.map(l => rightOf(l, 3, 6))));
  }
}
